name: Price Checker every 2 hours

on:
  schedule:
    - cron: "0 */2 * * *"
  workflow_dispatch:

jobs:
  checker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - run: python check_price.py
